name: Deploy StarCMS via SSH

on:
  # This workflow can be triggered manually from the GitHub Actions UI.
  # This is generally safer for deployments than triggering on every push.
  workflow_dispatch:

jobs:
  deploy:
    # Specify that this job should run on a self-hosted runner.
    runs-on: self-hosted

    # Define environment variables for SSH credentials.
    # It is HIGHLY recommended to store these as GitHub Secrets
    # (e.g., SSH_HOST, SSH_USERNAME, SSH_PASSWORD)
    # and reference them like ${{ secrets.SSH_HOST }} for security.
    env:
      SSHIP: ${{ vars.SSHIP }}       # Host IP address or hostname
      SSHUSER: ${{ vars.SSHUSER }}   # SSH username
      SSHPASS: ${{ secrets.SSHPASS }} # SSH password (store securely as a secret!)

    steps:
    - name: Checkout repository
      # This step is necessary to get your repository's code onto the runner,
      # which might be needed for other steps, though not strictly for this SSH command.
      uses: actions/checkout@v4

    - name: Install sshpass (if not already present on self-hosted runner)
      # sshpass is used to provide the password non-interactively to ssh.
      # This step assumes a Debian/Ubuntu-like system. Adjust for other OS.
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy via SSH
      # Use sshpass to provide the password and then execute commands on the remote machine.
      # The -o StrictHostKeyChecking=no and -o UserKnownHostsFile=/dev/null
      # are used to bypass host key checking, which is generally NOT recommended
      # for production environments due to security risks (Man-in-the-Middle attacks).
      # For better security, pre-add the host key to the runner's known_hosts file,
      # or use SSH keys instead of passwords.
      run: |
        sshpass -p "${{ env.SSHPASS }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        "${{ env.SSHUSER }}"@"${{ env.SSHIP }}" << 'EOF'
          # Navigate to the application directory
          cd /home/page-manager/StarCMS

          # Pull the latest changes from the Git repository
          echo "Running git pull..."
          git pull

          # Restart the page-writer service
          echo "Restarting page-writer.service..."
          sudo systemctl restart page-writer.service

          # Restart the page-reader service
          echo "Restarting page-reader.service..."
          sudo systemctl restart page-reader.service

          echo "Deployment complete."
        EOF
      # The 'EOF' marker ensures that all commands between the two 'EOF's are
      # executed on the remote server. The single quotes around 'EOF' prevent
      # shell variable expansion on the local runner before SSHing.
